"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var message = "Hello World!";
var amount = 23.423;
var error = "error msg";
console.log('Message (String):', message);
console.log('Message - upperCase (String):', message.toUpperCase());
console.log('Amount (Number):', amount);
console.log('Amount - to fixed (Number):', amount.toFixed(2));
console.log('Error:', error);
